### ISSUE TITLE
Cant see my twitter friends. Twitter authentication broken.

### ISSUE THREAD

**Issue by Usprogis** [M4t1ss/TwitEdiens#11]
http://twitediens.tk/draugi vietne nefunkcione. Vai nu jasalabo, vai ari janem nost...

**Comment by Usprogis** [comment]
http://twitediens.tk/draugi vietne nefunkcione. Vai nu jasalabo, vai ari janem nost...

**Comment by M4t1ss** [comment]
Tiešām? Ko Tev rāda? Man izskatās diezgan OK...
![image](https://user-images.githubusercontent.com/1122842/94018560-b4c25d00-fdeb-11ea-9fda-16a8fbf5d0ba.png)

**Comment by Usprogis** [comment]
![Screenshot from 2020-09-23 16-43-07](https://user-images.githubusercontent.com/25728446/94020799-005d1280-fdbc-11ea-87ad-2ed2de76c078.png)
Autorizacija nenostrada man... hmm...
